USE [master]
GO

/****** Object:  Database [_NEEDLE_SUPPLIER_]    Script Date: 11/1/2021 8:13:14 AM ******/
CREATE DATABASE [_NEEDLE_SUPPLIER_]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'_NEEDLE_SUPPLIER_', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\_NEEDLE_SUPPLIER_.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'_NEEDLE_SUPPLIER__log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\_NEEDLE_SUPPLIER__log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [_NEEDLE_SUPPLIER_].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ARITHABORT OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET  ENABLE_BROKER 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET  MULTI_USER 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET DB_CHAINING OFF 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [_NEEDLE_SUPPLIER_] SET  READ_WRITE 
GO

