//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CONFIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEvent
    {
        public int LogId { get; set; }
        public string Message { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Exception { get; set; }
        public string Properties { get; set; }
        public string MassageString { get; set; }
        public string DeviceID { get; set; }
    }
}
