//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CONFIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_Requests
    {
        public int RequestID { get; set; }
        public int DeviceID { get; set; }
        public int NeedleID { get; set; }
        public int RequestByStaffID { get; set; }
        public System.DateTime RequestTime { get; set; }
        public string RequestTimeStr { get; set; }
        public System.DateTime BrokenTime { get; set; }
        public string BrokenTimeStr { get; set; }
        public int Operator { get; set; }
        public int ProcessID { get; set; }
        public int SewingMachine { get; set; }
        public int ReasonID { get; set; }
        public int NeedlePartsEnough { get; set; }
        public string Handle { get; set; }
        public int Quantity { get; set; }
        public int AllowByStaffID { get; set; }
        public string PO { get; set; }
    
        public virtual NS_BrokenReason NS_BrokenReason { get; set; }
        public virtual NS_Devices NS_Devices { get; set; }
        public virtual NS_Needles NS_Needles { get; set; }
        public virtual NS_Process NS_Process { get; set; }
        public virtual NS_Requests NS_Requests1 { get; set; }
        public virtual NS_Requests NS_Requests2 { get; set; }
        public virtual NS_Staffs NS_Staffs { get; set; }
        public virtual NS_Staffs NS_Staffs1 { get; set; }
    }
}
