//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CONFIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_RecycledBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NS_RecycledBox()
        {
            this.NS_Export = new HashSet<NS_Export>();
        }
    
        public int RecycleBoxID { get; set; }
        public int DeviceID { get; set; }
        public int NeedleID { get; set; }
        public Nullable<System.DateTime> BrokenTime { get; set; }
        public string BrokenTimeStr { get; set; }
        public Nullable<int> Operator { get; set; }
        public string SewingMachine { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public System.DateTime ExportTime { get; set; }
        public string ExportTimeStr { get; set; }
        public int GetByStaffID { get; set; }
        public byte[] RecycleNeedleImage { get; set; }
        public Nullable<int> NeedlePartsEnough { get; set; }
        public Nullable<System.DateTime> ConfirmationTime { get; set; }
        public string ConfirmationTimeStr { get; set; }
        public Nullable<int> ConfirmationByStaffID { get; set; }
        public string Handle { get; set; }
        public string PO { get; set; }
        public Nullable<int> InBox { get; set; }
        public Nullable<decimal> CapturedLength { get; set; }
        public Nullable<int> DeleteByStaffID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string DeleteTimeStr { get; set; }
    
        public virtual NS_BrokenReason NS_BrokenReason { get; set; }
        public virtual NS_Devices NS_Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NS_Export> NS_Export { get; set; }
        public virtual NS_Needles NS_Needles { get; set; }
        public virtual NS_Process NS_Process { get; set; }
        public virtual NS_Staffs NS_Staffs { get; set; }
        public virtual NS_Staffs NS_Staffs1 { get; set; }
        public virtual NS_Staffs NS_Staffs2 { get; set; }
    }
}
