//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CONFIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_Stocks
    {
        public int StockID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> NeedleID { get; set; }
        public Nullable<int> CurrentQuantity { get; set; }
        public string NeedlePosition { get; set; }
    
        public virtual NS_Devices NS_Devices { get; set; }
        public virtual NS_Needles NS_Needles { get; set; }
    }
}
