//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CONFIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_Staffs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NS_Staffs()
        {
            this.NS_Export = new HashSet<NS_Export>();
            this.NS_Imports = new HashSet<NS_Imports>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public int CardNumber { get; set; }
        public string Department { get; set; }
        public int BuildingID { get; set; }
        public string RFIDCode { get; set; }
        public int DeviceID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserLayer { get; set; }
    
        public virtual NS_Buildings NS_Buildings { get; set; }
        public virtual NS_Devices NS_Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NS_Export> NS_Export { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NS_Imports> NS_Imports { get; set; }
    }
}
